"""Parser tag enumeration for categorizing parsers."""

from enum import StrEnum


class ParserTag(StrEnum):
    """Categorization tags for parsers with display-friendly values."""

    AAA = "AAA"
    ACL = "ACL"
    ARP = "ARP"
    BFD = "BFD"
    BGP = "BGP"
    CDP = "CDP"
    CONNECTIVITY = "Connectivity"
    DHCP = "DHCP"
    EIGRP = "EIGRP"
    ENVIRONMENT = "Environment"
    FHRP = "FHRP"
    INTERFACES = "Interfaces"
    INVENTORY = "Inventory"
    ISIS = "IS-IS"
    LAG = "LAG"
    LLDP = "LLDP"
    LOGGING = "Logging"
    MAC = "MAC"
    MACSEC = "MACsec"
    MPLS = "MPLS"
    MULTICAST = "Multicast"
    NAT = "NAT"
    OSPF = "OSPF"
    PLATFORM = "Platform"
    POE = "PoE"
    QOS = "QoS"
    REDUNDANCY = "Redundancy"
    ROUTING = "Routing"
    SDWAN = "SD-WAN"
    SECURITY = "Security"
    SNMP = "SNMP"
    STP = "STP"
    SWITCHING = "Switching"
    SYSTEM = "System"
    TRACKING = "Tracking"
    VLAN = "VLAN"
    VPC = "vPC"
    VPN = "VPN"
    VRF = "VRF"
    VTP = "VTP"
    VXLAN = "VXLAN"
